folder:
    checkpoint1: /Users/zhangkuang/Documents/Desk/kuangkaungkaungha/Go-for-waiting/readText/新建文件.txt
    checkpoint2: ../readText/haha.txt
    checkpoint3: ../readText/wawa.txt

class: 517
floor: 4